/**
 * Single source of truth for unit-test coverage scope and thresholds.
 *
 * Consumed by vitest.config.ts (enforced on every `npm run test:unit:coverage`)
 * and scripts/check-coverage.mjs (re-checks merged unit + Playwright output).
 */

/** Every metric must meet this minimum, globally and per functional area. */
export const MINIMUM = 85;

export const METRICS = /** @type {const} */ (["statements", "branches", "functions", "lines"]);

/**
 * All application source is measured, including files no test imports
 * (Istanbul reports those as 0% instead of silently skipping them).
 */
export const COVERAGE_INCLUDE = [
  "src/**/*.{ts,tsx}",
  "shared/**/*.ts",
  "convex/**/*.ts",
  "security/**/*.ts",
];

/**
 * Exclusions are limited to generated code, type declarations, deployment
 * configuration, and static data. Each entry states why it is excluded.
 */
export const COVERAGE_EXCLUDE_REASONS = {
  "**/*.d.ts": "Type declarations: no runtime code.",
  "convex/_generated/**": "Generated by `convex dev` codegen (or the local server stub).",
  "convex/auth.config.ts": "Deployment configuration read by the Convex platform, not executed by app code.",
  "convex/crons.ts": "Declarative cron schedule registered by the Convex platform; the scheduled mutation is tested directly.",
  "shared/registration/countries.ts": "Static data generated by scripts/generate-countries.mjs.",
  "shared/registration/mlhSchools.ts": "Static data generated by scripts/generate-mlh-schools.mjs.",
};

export const COVERAGE_EXCLUDE = Object.keys(COVERAGE_EXCLUDE_REASONS);

/**
 * Major functional areas. Each area must independently meet MINIMUM in every
 * metric, so a well-tested utility layer cannot mask an untested workflow.
 */
export const COVERAGE_AREAS = {
  "Shared validation, drafts, and error mapping": "shared/**",
  "Backend (Convex queries, mutations, HTTP, email)": "convex/**",
  "Security headers": "security/**",
  "Authentication UI and session": "{src/pages/SignIn/**,src/hooks/**,src/components/{AuthBootstrap,MockAuthProvider,OtpCodeInput,ProtectedRoute,SignOutButton}.tsx,src/constants/mockAuth.ts}",
  "Registration UI": "src/pages/Register/**",
  "Profile UI": "src/pages/Profile/**",
  "App shell and presentation": "{src/main.tsx,src/pages/HomeRedirect.tsx,src/convex/**,src/constants/{images,signInWeather,site}.ts,src/components/{OdysseyButton,PageShell,SignInAtmosphere,SignInShell,SignInStormBackdrop,StormPageFrame,WeatherMoodToggle}.tsx,src/components/art/**}",
};

const allMetrics = Object.fromEntries(METRICS.map((metric) => [metric, MINIMUM]));

/** Vitest `coverage.thresholds` object: global minimums plus one glob per area. */
export const VITEST_THRESHOLDS = {
  ...allMetrics,
  ...Object.fromEntries(Object.values(COVERAGE_AREAS).map((glob) => [glob, { ...allMetrics }])),
};
